dependencies {
    api project(':api')

    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test { useJUnitPlatform() }
